# 多数据源用法，同spring-boot2-mysql-multi-datasource项目一样
spring:
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db1?autoReconnect=true&useunicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: root